# Generated by Django 4.2 on 2023-05-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('PLK', 'Polokwane'), ('WC', 'Western-Cape'), ('NW', 'North-West'), ('EC', 'Easten-Cape'), ('GP', 'Gauteng'), ('MP', 'Mpumalanga'), ('PE', 'Portelizabeth')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('MS', 'Moisture'), ('CM', 'Combos'), ('CR', 'Cream'), ('BL', 'Balm'), ('WS', 'Wash'), ('SR', 'Serun')], max_length=2),
        ),
    ]
