# Generated by Django 5.0.2 on 2024-02-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('PE', 'Portelizabeth'), ('EC', 'Easten-Cape'), ('NW', 'North-West'), ('PLK', 'Polokwane'), ('WC', 'Western-Cape'), ('MP', 'Mpumalanga'), ('GP', 'Gauteng')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('On The Way', 'On The Way'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('SR', 'Serun'), ('BL', 'Balm'), ('CR', 'Cream'), ('CM', 'Combos'), ('MS', 'Moisture'), ('WS', 'Wash')], max_length=2),
        ),
    ]
